### ISSUE TITLE
How to evaluate the trained models' performance?

### ISSUE THREAD

**Issue by yashbhalgat** [HengyiWang/neural-rgbd-torch#2]
Hi @HengyiWang, thanks again for the great work!

I was able to train a model for 200000 iterations and the results look "visually" good. However, I want to evaluate the performance quantitatively and compare it to the numbers reported in the [paper](https://arxiv.org/pdf/2104.04532.pdf).

Do you have some script to evaluate the final performance and get the metrics? It would be very helpful!

Thanks.

**Comment by HengyiWang** [comment]
Hi @yashbhalgat, sorry the current eval script I am using is in a slightly different setting, and it is from another paper that has not yet been available. But I suggest you contact the author of the NeuralRGBD as the eval script does not make any difference once you got the mesh.

**Comment by yashbhalgat** [comment]
No problem. Yes, I contacted the NeuralRGBD author regarding the same.
